### ISSUE TITLE
question name modal color issue.

### ISSUE THREAD

**Issue by AhmadHerzallah** [HatemSaadallah/cfp-code-submitter#9]
after sending the code. fixed question name in the modal (color).
![Screenshot from 2020-10-08 00-26-06](https://user-images.githubusercontent.com/43403487/95440054-1bee1e80-0961-11eb-896f-65fbe9b14a0d.jpg)

**Comment by AhmadHerzallah** [comment]
PR: #10

**Comment by HatemSaadallah** [comment]
Done fixed.
